version: 3

auth:
  session_key: "x-sessionID"
  logout_key: "logout"
database:
  dsn: "host=%s port=%s dbname=%s user=%s password=%s sslmode=%s"
  dbname: "user-api"
  host: "62.84.127.244"
  port: "5432"
  user: "user-api"
  password: "password"
  ssl: "disable"
redis:
  host: "62.84.127.244"
  port: "6379"
  password: ""
app:
  http_port: "8080"
  grpc_port: "8082"